In [1]:
"""
@filename: Numpy.py
@author: waisullah yousofi
@url: https://docs.scipy.org/doc/numpy/user/index.html
@url: https://docs.scipy.org/doc/numpy/user/quickstart.html
"""

'\n@filename: Numpy.py\n@author: cyruslentin\n@url: https://docs.scipy.org/doc/numpy/user/index.html\n@url: https://docs.scipy.org/doc/numpy/user/quickstart.html\n'

Numpy<br>
Numpy is the core library for scientific computing in Python. It provides a <br>
high-performance multidimensional array object, and tools for working with <br>
these arrays. 

Arrays<br>
A numpy array is a grid of values, all of the same type, and is indexed by  <br>
nonnegative integers. The number of dimensions is the rank of the <br>
array; the shape of an array is integers giving the size of the <br>
array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements <br>
using square brackets:

Array Properties    <br>
ndarray.ndim<br>
the number of axes (dimensions) of the array. In the Python world, the number <br>
of dimensions is referred to as rank.<br>
ndarray.shape<br>
the dimensions of the array. This is number of integers indicating the size <br>
of the array in each dimension. For a matrix with n rows and m columns, <br>
shape will be (n,m). The length of the shape is therefore the rank, or <br>
number of dimensions, ndim.<br>
ndarray.size<br>
the total number of elements of the array. This is equal to the product of <br>
the elements of shape.<br>
ndarray.dtype<br>
an object describing the type of the elements in the array. One can create or <br>
specify dtype’s using standard Python types. Additionally NumPy provides types <br>
of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.<br>
ndarray.itemsize<br>
the size in bytes of each element of the array. For example, an array of <br>
elements of type float64 has itemsize 8 (=64/8), while one of type complex32 <br>
has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

In [2]:
   
# import   
import numpy as np

In [3]:
l = [1,2,3]
print(l)

[1, 2, 3]


create array

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# print
print(a)
# dim
print(a.ndim)
# shape
print(a.shape)
# type
print(type(a))
# type
print(a.dtype.name)
# item size
print(a.itemsize)
# size
print(a.size)
# size
print(len(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
<class 'numpy.ndarray'>
int32
4
12
12


create array

In [5]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# print
print(a)
# dim
print(a.ndim)
# shape
print(a.shape)
# type
print(type(a))
# type
print(a.dtype.name)
# item size
print(a.itemsize)
# size
print(a.size)
# size
print(len(a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)
<class 'numpy.ndarray'>
int32
4
12
3


Array Creation

In [6]:
a = np.array([2,3.5,4])
print(a)
print(a.dtype)
a = np.array([1.2, 3.5, 5.1])
print(a)
print(a.dtype)

[2.  3.5 4. ]
float64
[1.2 3.5 5.1]
float64


Array Creation - Error

In [7]:
a = np.array(1,2,3,4)    # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [ ]:
a = np.array([1,2,3,4])  # RIGHT
print(a)
print(a.dtype)

In [ ]:
a = np.array([1.0,2,3,4])  # RIGHT
print(a)
print(a.dtype)

In [8]:
a = np.array([1,2,3,4], dtype=np.float64 )  
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float64


In [9]:
a = np.array([1,2,3,4], dtype=np.int64 )
print(a)
print(a.dtype)

[1 2 3 4]
int64


In [10]:
a = np.array([1.1,2.2,3.3,4.4,5.5,6.6], dtype=np.int32 )  
print(a)
print(a.dtype)

[1 2 3 4 5 6]
int32


create array of zeros

In [11]:
a = np.zeros( (3,4) )
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


create array of ones

In [12]:
a = np.ones( (3,4), dtype=np.int16 )                # dtype can also be specified
print(a)
print(a.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int16


create array of ones

In [13]:
a = np.ones( (2,3,4), dtype=np.float64 )                # dtype can also be specified
print(a)
print(a.dtype)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
float64


create array using sequences of numbers, NumPy provides a function analogous <br>
to range that returns arrays instead of lists.

In [14]:
a = np.arange(15)
print(a)
a = np.arange( 0, 15)
print(a)
a = np.arange( 10, 30, 5 )
print(a)
a = np.arange( 0, 2, 0.3 )                 # it accepts float arguments
print(a)
a = np.arange(15).reshape(3, 5)
print(a)
a = np.arange(15).reshape(3, 6)
print(a)
a = np.arange(27).reshape(3, 3, 3)
print(a)
a = np.arange(10000)
print(a)
a = np.arange(10000).reshape(100,100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


ValueError: cannot reshape array of size 15 into shape (3,6)

arithmetic operations

In [15]:
a = np.array( [20, 30, 40, 50, 60] )
b = np.arange( 4 )
print(a)
print(b)

[20 30 40 50 60]
[0 1 2 3]


an array with a number<br>
what is the return data type

addition

In [16]:
c = a + 10
print("a + 10:")
print(c)

a + 10:
[30 40 50 60 70]


subtract

In [17]:
c = a - 10
print("a - 10:")
print(c)

a - 10:
[10 20 30 40 50]


multiplication

In [18]:
c = a * 10
print("a * 10:")
print(c)

a * 10:
[200 300 400 500 600]


division

In [19]:
c = a / 10
print("a / 10:")
print(c)

a / 10:
[2. 3. 4. 5. 6.]


raise to

In [20]:
c = a ** 2
print("a ** 2:")
print(a)
print(c)

a ** 2:
[20 30 40 50 60]
[ 400  900 1600 2500 3600]


an array with another array<br>
what is the return data type<br>
arithmetic operations

In [21]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


addition 

In [22]:
c = a + b
print("a + b:")
print(c)

a + b:
[20 31 42 53]


subtraction

In [23]:
c = a - b
print("a - b:")
print(c)

a - b:
[20 29 38 47]


multiplication

In [24]:
c = a * b
print("a * b:")
print(c)

a * b:
[  0  30  80 150]


division

In [25]:
c = a / b
print("a / b:")
print(c)

a / b:
[        inf 30.         20.         16.66666667]


<ipython-input-25-d7f40701ef79>:1: RuntimeWarning: divide by zero encountered in true_divide
  c = a / b


raise to

In [26]:
c = a ** b
print("a ^ b:")
print(c)

a ^ b:
[     1     30   1600 125000]


an array with another array<br>
what is the return data type<br>
arithmetic operations

In [27]:
a = np.array( [20,30,40,50] )
b = np.arange( 3 )
print(a)
print(b)

[20 30 40 50]
[0 1 2]


addition 

In [28]:
c = a + b
print("a + b:")
print(c)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

two dim array

In [29]:
a = np.array( [ [2,2], [2,2] ] )
b = np.array( [ [2,2], [2,2] ] )
print(a)
print(b)

[[2 2]
 [2 2]]
[[2 2]
 [2 2]]


addition

In [30]:
c = a + b
print("a + b:")
print(c)

a + b:
[[4 4]
 [4 4]]


subtract

In [31]:
c = a - b
print("a - b:")
print(c)

a - b:
[[0 0]
 [0 0]]


multiply 

In [32]:
c = a * b
print("a * b:")
print(c)

a * b:
[[4 4]
 [4 4]]


division

In [33]:
c = a / b
print("a / b:")
print(c)

a / b:
[[1. 1.]
 [1. 1.]]


ttps://matrix.reshish.com/multiplication.php

two dim array

In [34]:
a = np.array( [ [2,2], [2,2] ] )
b = np.array( [ [2,2], [2,2] ] )
print(a)
print(b)

[[2 2]
 [2 2]]
[[2 2]
 [2 2]]


dot product

In [35]:
c = np.dot(a,b)
print("np.dot(a,b)")
print(c)

np.dot(a,b)
[[8 8]
 [8 8]]


two dim array

In [36]:
a = np.arange(6).reshape(2,3)
b = np.array([6,7,8,9,10,11]).reshape(3,2)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


multiply 

In [37]:
c = a * b
print("a * b:")
print(c)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

dot product

In [38]:
c = np.dot(a,b)
print("np.dot(a,b)")
print(c)

np.dot(a,b)
[[ 28  31]
 [100 112]]


two dim array

In [39]:
a = np.arange(10).reshape(5,2)
b = np.array([6,7,8,9,10,11]).reshape(2,3)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 6  7  8]
 [ 9 10 11]]


dot product

In [40]:
c = np.dot(a,b)
print("np.dot(a,b)")
print(c)

np.dot(a,b)
[[  9  10  11]
 [ 39  44  49]
 [ 69  78  87]
 [ 99 112 125]
 [129 146 163]]


dot product

In [41]:
c = np.dot(b,a)
print("np.dot(b,a)")
print(c)

ValueError: shapes (2,3) and (5,2) not aligned: 3 (dim 1) != 5 (dim 0)

in place arithmetic operations

In [42]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
#b = np.array( [2,3,4,5]  )
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


addition

In [43]:
a += b 
print("a += b:")
print(a)

a += b:
[20 31 42 53]


subtraction

In [44]:
a -= b 
print("a -= b:")
print(a)

a -= b:
[20 30 40 50]


multiplication

In [45]:
a *= b 
print("a *= b:")
print(a)

a *= b:
[  0  30  80 150]


division

In [46]:
print(a)
print(b)
a /= b 
print("a /= b:")
print(a)

[  0  30  80 150]
[0 1 2 3]


TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

division

In [47]:
a = np.array( [20.0,30,40,50] )
b = np.array( [2,3,4,5]  )
print(a)
print(b)
a /= b 
print("a /= b:")
print(a)

[20. 30. 40. 50.]
[2 3 4 5]
a /= b:
[10. 10. 10. 10.]


universal functions

In [48]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


count

In [49]:
x = a.size
print(x)

12


sum

In [50]:
x = a.sum()
print(x)

78


min

In [51]:
x = a.min()
print(x)

1


max

In [52]:
x = a.max()
print(x)

12


max

In [53]:
x = a.mean()
print(x)

6.5


universal functions

In [54]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


sum rows

In [55]:
x = a.sum(axis=0)
print(x)

[15 18 21 24]


min row

In [56]:
x = a.min(axis=0)
print(x)

[1 2 3 4]


max rows

In [57]:
x = a.max(axis=0)
print(x)

[ 9 10 11 12]


universal functions

In [58]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(type(a))
print(a.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
int32


sum cols

In [59]:
x = a.sum(axis=1)
print(x)

[10 26 42]


min cols

In [60]:
x = a.min(axis=1)
print(x)

[1 5 9]


max cols

In [61]:
x = a.max(axis=1)
print(x)

[ 4  8 12]


===================================================

indexing / slicing / iterating<br>
one-dimensional arrays can be indexed, sliced and iterated over, much like <br>
lists and other Python sequences.

print 3 rd element

In [62]:
a = np.arange(10, 50, 5 )
print(a)
print(a[2])
a[2] = 0
print(a[2])
print(a)

[10 15 20 25 30 35 40 45]
20
0
[10 15  0 25 30 35 40 45]


In [63]:
a = np.arange(10, 50, 5 )
print(a)
print(a[2:5])

[10 15 20 25 30 35 40 45]
[20 25 30]


In [64]:
a = np.arange(15).reshape(3, 5)
print(a)
print(a[2,2])
a[2,2] = 0
print(a[2,2])
print(a)
 
# print element n:m
a = np.arange(10)
print(a)
print(a[2:5])
a[2:5] = 0
print(a[2:5])
print(a)
a[2:5] = [ 10, 20, 30]
print(a[2:5])
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
12
0
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0 13 14]]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 0 0]
[0 1 0 0 0 5 6 7 8 9]
[10 20 30]
[ 0  1 10 20 30  5  6  7  8  9]


In [65]:
a = np.arange(15).reshape(3, 5)
print(a)
print(a[2,2:4])
a[2,2:4] = 0
print(a)
a[2,2:4] = 100
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[12 13]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  0 14]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11 100 100  14]]


In [66]:
a = np.arange(15).reshape(3, 5)
print(a)
print(a[2,:])
a[2,:] = 0
print(a)
a[2,:] = 100
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[10 11 12 13 14]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 0 0 0 0]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [100 100 100 100 100]]


In [67]:
a = np.arange(15).reshape(3, 5)
print(a)
print(a[1:3,2])
a[1:3,2] = 0
print(a)
a[1:3,2] = 100
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 7 12]
[[ 0  1  2  3  4]
 [ 5  6  0  8  9]
 [10 11  0 13 14]]
[[  0   1   2   3   4]
 [  5   6 100   8   9]
 [ 10  11 100  13  14]]


In [68]:
a = np.arange(15).reshape(3, 5)
print(a)
print(a[:,2])
a[:,2] = 0
print(a)
a[:,2] = 100
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 2  7 12]
[[ 0  1  0  3  4]
 [ 5  6  0  8  9]
 [10 11  0 13 14]]
[[  0   1 100   3   4]
 [  5   6 100   8   9]
 [ 10  11 100  13  14]]


print element n:m:s

In [69]:
a = np.arange(20)
print(a)
print(a[2:12:2])
a[2:12:2] = 0
print(a[2:12:2])
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10]
[0 0 0 0 0]
[ 0  1  0  3  0  5  0  7  0  9  0 11 12 13 14 15 16 17 18 19]


append element 

In [70]:
a = np.arange(20)
print(a)
a = np.append(a,[100,105,110])
print(a)
a = np.append(a,np.arange(10))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 100 105 110]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 100 105 110   0   1   2   3   4   5   6   7   8   9]


append row

In [71]:
a = [[1, 2, 3], [4, 5, 6]]
print(a)
a = np.append(a, [[7, 8, 9]], axis=0)
print(a)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


append row

In [72]:
a = [[1, 2], [3, 4], [5, 6]]
print(a)
a = np.append(a, [[7, 8]], axis=0)
print(a)

[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


insert element

In [73]:
a = np.arange(20)
print(a)
a = np.insert(a, 3, [100,101,103], axis=0)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2 100 101 103   3   4   5   6   7   8   9  10  11  12  13  14
  15  16  17  18  19]


insert row

In [74]:
a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)
a = np.insert(a, 1, [[5,6]], axis=0)
print(a)

[[1 1]
 [2 2]
 [3 3]]
[[1 1]
 [5 6]
 [2 2]
 [3 3]]


insert col

In [75]:
a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)
a = np.insert(a, 1, [[5,6,7]], axis=1)
print(a)

[[1 1]
 [2 2]
 [3 3]]
[[1 5 1]
 [2 6 2]
 [3 7 3]]


delete element

In [76]:
a = np.arange(20)
print(a)
a = np.delete(a,1)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


delete element

In [77]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


delete row

In [78]:
a = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(a)
print("")
a = np.delete(a, 1, axis=0)
print(a)

[[11 12 13]
 [21 22 23]
 [31 32 33]]

[[11 12 13]
 [31 32 33]]


delete col

In [79]:
a = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(a)
print("")
a = np.delete(a, 2, axis=1)
print(a)

[[11 12 13]
 [21 22 23]
 [31 32 33]]

[[11 12]
 [21 22]
 [31 32]]


loops

In [80]:
a = np.arange(10)
print(a)
for i in a:
    print(i*i)

[0 1 2 3 4 5 6 7 8 9]
0
1
4
9
16
25
36
49
64
81


In [81]:
a = np.arange(42).reshape(6,7)
print(a)
print(a[3:5,3:5])
print(a[4,2:6])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
[[24 25]
 [31 32]]
[30 31 32 33]


indexing / slicing / iterating<br>
two-dimensional arrays can be indexed, sliced and iterated over

print single element

In [82]:
a = np.arange(25).reshape(5,5)
print(a)
print(a[0,0])
a[0,0] = 999
print(a[0,0])
print(a)
 
# print rows or cols
a = np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
0
999
[[999   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


each row in the second column

In [83]:
print(a[0:5,1])

[ 1  6 11 16 21]


equivalent to the previous example

In [84]:
print(a[ : ,1]) 

[ 1  6 11 16 21]


all elements

In [85]:
print(a[:,:]) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


each column in the second and third row 

In [86]:
print(a[1:3, : ])                      

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


when fewer indices are provided than the number of axes, <br>
the missing indices are considered complete slices:<br>
the last row. Equivalent to b[-1,:]

In [87]:
print(a[-1])

[20 21 22 23 24]


In [88]:
print(a[:,-1])

[ 4  9 14 19 24]


In [89]:
print(a[-1,-1])

24


loops

In [90]:
a = np.arange(10)
print(a)
for i in a:
    i=i+2
    print(i)

[0 1 2 3 4 5 6 7 8 9]
2
3
4
5
6
7
8
9
10
11


loops

In [91]:
a = np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


iterate rows

In [92]:
for row in a:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


iterate cols<br>
run for loop in transpose of an array

In [93]:
for col in a.T:
    print(col)

[ 0  5 10 15 20]
[ 1  6 11 16 21]
[ 2  7 12 17 22]
[ 3  8 13 18 23]
[ 4  9 14 19 24]


if one wants to perform an operation on each element in the array, <br>
one can use the flat attribute which is an iterator over all the elements of the array:

In [94]:
a = np.arange(25).reshape(5,5)
print(a)
for item in a.flat:
    print(item)
    
# loop in i,j
a = np.arange(20).reshape(5,4)
print(a)
print(a.shape)
print(type(a))
rows = a.shape[0]
print("Rows:")
print(rows)
cols = a.shape[1]
print("Cols:")
print(cols)
for row in range(rows):
    for col in range(cols):
        print(a[row,col])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)
<class 'numpy.ndarray'>
Rows:
5
Cols:
4
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


copy<br>
the copy method makes a complete copy of the array and its data.

In [95]:
a = np.arange(16).reshape(4,4)
b = a
c = a.copy()
print(a)
print(b)
print(c)
# b & a is same
print(b is a)
# c & a is same
print(c is a)
# b is a ... copy of the data owned by a?
print(b.base is a.base) 
# c is a ... copy of the data owned by a?
print(c.base is a.base) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
True
False
True
False


data changes in c

In [96]:
a = np.arange(16).reshape(4,4)
b = a
c = a.copy()
print(a)
print(b)
print(c)
a[0,0] = 999
print(a)
print(b)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


data changes in a

In [97]:
a = np.arange(16).reshape(4,4)
b = a
print(a)
print(b)
a[1,1] = 888
b[0,0] = 999

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [98]:
print(a)
print(b)
c = a.copy()
print(a)
print(b)
print(c)

[[999   1   2   3]
 [  4 888   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[[999   1   2   3]
 [  4 888   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[[999   1   2   3]
 [  4 888   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[[999   1   2   3]
 [  4 888   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[[999   1   2   3]
 [  4 888   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


view or Shallow Copy<br>
different array objects can share the same data. The view method creates a <br>
new array object that looks at the same data.

In [99]:
a = np.arange(16).reshape(4,4)
v = a.view()
print(a)
print(v)
# v & a is same
print(v is a)
# c is a view of the data owned by a
print(v.base is a.base) 
# data changes in both
v[0,0] = 999
print(a)
print(v)
# data changes in both
a[3,3] = 999
print(a)
print(v)
 
# simple assignments do not make the copy of array
# object. Instead, it uses the same id() of the 
# original array to access it. The id() returns a 
# universal identifier of Python object, similar 
# to the pointer in C.
# Furthermore, any changes in either gets reflected 
# in the other. For example, the changing shape of 
# one will change the shape of the other too.
a = np.arange(6) 
print('Our array is:') 
print(a)  
print('id() of a:') 
print(id(a))  
print('a is assigned to b:') 
b = a 
print(b)  
print('id() of b:') 
print(id(b))  
print('id() of a == id() of b') 
print(id(a) == id(b))
print('Change shape of b:') 
b.shape=(3,2) 
print(b)
print('Shape of a also gets changed:')
print(a)
# b & a is same
print(b is a)
# b is a view of the data owned by a
print(b.base is a.base) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
False
True
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14 999]]
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14 999]]
Our array is:
[0 1 2 3 4 5]
id() of a:
2212888294384
a is assigned to b:
[0 1 2 3 4 5]
id() of b:
2212888294384
id() of a == id() of b
True
Change shape of b:
[[0 1]
 [2 3]
 [4 5]]
Shape of a also gets changed:
[[0 1]
 [2 3]
 [4 5]]
True
True


NumPy has ndarray.view() method which is a new <br>
array object that looks at the same data of the <br>
original array. Unlike the earlier case, change <br>
in dimensions of the new array doesn’t change <br>
dimensions of the original.<br>
To begin with, a is 3X2 array 

In [100]:
a = np.arange(6).reshape(3,2) 
print('Array a:')
print(a)  
print('Create view of a:') 
b = a.view() 
print(b)  
print('id() for both the arrays are different:') 
print('id() of a:')
print(id(a))  
print('id() of b:') 
print(id(b))
# Change the shape of b. It does not change the shape of a 
b.shape = 2,3 
print('Shape of b:') 
print(b)  
print('Shape of a:') 
print(a)
# b & a is same
print(b is a)
# b is a view of the data owned by a
print(b.base is a.base) 

Array a:
[[0 1]
 [2 3]
 [4 5]]
Create view of a:
[[0 1]
 [2 3]
 [4 5]]
id() for both the arrays are different:
id() of a:
2212904979072
id() of b:
2212904976912
Shape of b:
[[0 1 2]
 [3 4 5]]
Shape of a:
[[0 1]
 [2 3]
 [4 5]]
False
True


The ndarray.copy() function creates a deep copy. <br>
It is a complete copy of the array and its data, <br>
and doesn’t share with the original array.

In [101]:
a = np.array([[10,10], [2,3], [4,5]]) 
print('Array a is:')
print(a)  
print('Create a deep copy of a:') 
b = a.copy() 
print('Array b is:') 
print(b)
print('Change the contents of b:') 
b[0,0] = 100 
print('Modified array b:')
print(b)  
print('a remains unchanged:') 
print(a)
# b & a is same
print(b is a)
# b is a view of the data owned by a
print(b.base is a.base) 

Array a is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Create a deep copy of a:
Array b is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Change the contents of b:
Modified array b:
[[100  10]
 [  2   3]
 [  4   5]]
a remains unchanged:
[[10 10]
 [ 2  3]
 [ 4  5]]
False
True


In [102]:
a = np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


rint item 12

In [103]:
print(a[2,2])

12


second row

In [104]:
print(a[1,:])

[5 6 7 8 9]


fourth col

In [105]:
print(a[:,3])

[ 3  8 13 18 23]


vals 6 7 8

In [106]:
print(a[1,1:4])

[6 7 8]


vals 14 19 24

In [107]:
print(a[2:,4])

[14 19 24]
